// examples/angular/src/app/products.page.ts
import { NgFor, NgIf } from "@angular/common";
import { Component, OnInit } from "@angular/core";
import { Router } from "@angular/router";

import { listProducts, type Product } from "./api";

@Component({
  standalone: true,
  imports: [NgFor, NgIf],
  template: `
    <h1>Products</h1>
    <p class="error" *ngIf="error">{{ error }}</p>
    <article class="card" *ngFor="let product of products">
      <h2>{{ product.name }}</h2>
      <p>{{ product.description }}</p>
      <p><strong>{{ product.price }} {{ product.currency }}</strong></p>
      <button type="button" (click)="pay(product.id)">Pay</button>
    </article>
  `,
})
export class ProductsPageComponent implements OnInit {
  products: Product[] = [];
  error: string | null = null;

  constructor(private readonly router: Router) {}

  ngOnInit(): void {
    void listProducts()
      .then((items) => (this.products = items))
      .catch((err: Error) => (this.error = err.message));
  }

  pay(id: number): void {
    void this.router.navigate(["/pay", id]);
  }
}

// examples/vue/src/ProductsPage.vue
<script setup lang="ts">
import { onMounted, ref } from "vue";
import { useRouter } from "vue-router";

import { listProducts, type Product } from "./api";

const router = useRouter();
const products = ref<Product[]>([]);
const error = ref<string | null>(null);

onMounted(async () => {
  try {
    products.value = await listProducts();
  } catch (err) {
    error.value = (err as Error).message;
  }
});
</script>

<template>
  <h1>Products</h1>
  <p v-if="error" class="error">{{ error }}</p>
  <article v-for="product in products" :key="product.id" class="card">
    <h2>{{ product.name }}</h2>
    <p>{{ product.description }}</p>
    <p>
      <strong>{{ product.price }} {{ product.currency }}</strong>
    </p>
    <button type="button" @click="router.push(`/pay/${product.id}`)">Pay</button>
  </article>
</template>
