// examples/angular/src/app/refund.page.ts
import { NgFor, NgIf } from "@angular/common";
import { Component, OnInit } from "@angular/core";

import { listOrders, refundOrder, type Order } from "./api";

@Component({
  standalone: true,
  imports: [NgFor, NgIf],
  template: `
    <h1>Refund</h1>
    <p class="error" *ngIf="error">{{ error }}</p>
    <p *ngIf="orders.length === 0">No orders yet. Pay for a product first.</p>
    <article class="card" *ngFor="let order of orders">
      <p>Ref {{ order.reference }} — {{ order.amount }} {{ order.currency }} — <strong>{{ order.status }}</strong></p>
      <button *ngIf="order.status === 'paid'" type="button" (click)="refund(order.id)">Refund</button>
    </article>
  `,
})
export class RefundPageComponent implements OnInit {
  orders: Order[] = [];
  error: string | null = null;

  ngOnInit(): void {
    this.reload();
  }

  reload(): void {
    void listOrders()
      .then((items) => (this.orders = items))
      .catch((err: Error) => (this.error = err.message));
  }

  refund(id: number): void {
    void refundOrder(id)
      .then(() => this.reload())
      .catch((err: Error) => (this.error = err.message));
  }
}

// examples/vue/src/RefundPage.vue
<script setup lang="ts">
import { onMounted, ref } from "vue";

import { listOrders, refundOrder, type Order } from "./api";

const orders = ref<Order[]>([]);
const error = ref<string | null>(null);

async function reload(): Promise<void> {
  try {
    orders.value = await listOrders();
  } catch (err) {
    error.value = (err as Error).message;
  }
}

onMounted(() => {
  void reload();
});
</script>

<template>
  <h1>Refund</h1>
  <p v-if="error" class="error">{{ error }}</p>
  <p v-if="orders.length === 0">No orders yet. Pay for a product first.</p>
  <article v-for="order in orders" :key="order.id" class="card">
    <p>Ref {{ order.reference }} — {{ order.amount }} {{ order.currency }} — <strong>{{ order.status }}</strong></p>
    <button v-if="order.status === 'paid'" type="button" @click="refundOrder(order.id).then(reload).catch((err: Error) => (error = err.message))">
      Refund
    </button>
  </article>
</template>
