// examples/vue/src/App.vue
<script setup lang="ts">
import { backendUrl } from "./api";
</script>

<template>
  <nav>
    <router-link to="/">Products</router-link>
    <router-link to="/refund">Refund</router-link>
    <router-link to="/transfer">Transfer</router-link>
    <span style="margin-left: auto; color: #aaa">backend {{ backendUrl() }}</span>
  </nav>
  <main>
    <router-view />
  </main>
</template>

// examples/angular/src/app/app.component.ts
import { Component } from "@angular/core";
import { RouterLink, RouterOutlet } from "@angular/router";

import { backendUrl } from "./api";

@Component({
  selector: "app-root",
  standalone: true,
  imports: [RouterLink, RouterOutlet],
  template: `
    <nav>
      <a routerLink="/">Products</a>
      <a routerLink="/refund">Refund</a>
      <a routerLink="/transfer">Transfer</a>
      <span style="margin-left:auto;color:#aaa">backend {{ backend }}</span>
    </nav>
    <main>
      <router-outlet />
    </main>
  `,
})
export class AppComponent {
  readonly backend = backendUrl();
}
